server:
  port: 9001
spring:
  application:
    name: nacos-provider-payment
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.11.86:8888

management:
  endpoints:
    web:
      exposure:
        include: '*'